# Generated by Django 5.2.17 on 2026-08-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_add_cover_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricereference',
            name='currency',
            field=models.CharField(default='تومان', max_length=8),
        ),
    ]
