# Generated by Django 5.2.17 on 2026-08-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='youtube/covers/'),
        ),
    ]
