# Generated by Django 5.2.17 on 2026-08-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_currency_default_toman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('تومان', 'Iran (تومان)'), ('IRR', 'Iran (IRR)'), ('USD', 'United States (USD)'), ('AED', 'United Arab Emirates (AED)'), ('EUR', 'Euro (EUR)')], default='تومان', max_length=8),
        ),
    ]
