# Generated by Django 5.2.17 on 2026-08-07 21:25

import django.db.models.deletion
from django.db import migrations, models


def migrate_trim_strings(apps, schema_editor):
    Car = apps.get_model("cars", "Car")
    Trim = apps.get_model("cars", "Trim")
    for car in Car.objects.all().iterator():
        name = (car.trim_name or "").strip() or "Base"
        trim, _ = Trim.objects.get_or_create(car_model_id=car.model_id, name=name)
        car.trim_id = trim.pk
        car.save(update_fields=["trim_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_add_cover_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatterySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size', models.CharField(blank=True, max_length=20)),
                ('voltage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cca', models.PositiveIntegerField(blank=True, null=True)),
                ('chemistry', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'battery specs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('تومان', 'Iran (تومان)'), ('IRR', 'Iran (IRR)'), ('USD', 'United States (USD)'), ('AED', 'United Arab Emirates (AED)'), ('EUR', 'Euro (EUR)')], default='تومان', max_length=8)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cars.car')),
            ],
            options={
                'ordering': ['-recorded_at', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('brands', models.ManyToManyField(blank=True, related_name='dealers', to='cars.brand')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('wheelbase_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('curb_weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('cargo_l', models.PositiveIntegerField(blank=True, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ground_clearance_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_tank_l', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='cars.car')),
            ],
            options={
                'verbose_name_plural': 'dimensions',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('comfort', 'Comfort'), ('tech', 'Tech'), ('exterior', 'Exterior'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, max_length=160)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FluidSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid_type', models.CharField(choices=[('engine_oil', 'Engine oil'), ('coolant', 'Coolant'), ('brake', 'Brake fluid'), ('transmission', 'Transmission fluid'), ('washer', 'Washer fluid'), ('other', 'Other')], max_length=20)),
                ('specification', models.CharField(blank=True, max_length=120)),
                ('capacity', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluids', to='cars.car')),
            ],
            options={
                'ordering': ['fluid_type'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_months', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_items', to='cars.car')),
            ],
            options={
                'ordering': ['interval_km', 'interval_months', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('oem_number', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cars.car')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepairShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('brands', models.ManyToManyField(blank=True, related_name='repair_shops', to='cars.brand')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('months', models.PositiveIntegerField(blank=True, null=True)),
                ('tasks', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedule', to='cars.car')),
            ],
            options={
                'ordering': ['sort_order', 'mileage_km', 'months'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(blank=True, max_length=120)),
                ('displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('cylinders', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=80)),
                ('drivetrain', models.CharField(blank=True, max_length=40)),
                ('top_speed_kmh', models.PositiveIntegerField(blank=True, null=True)),
                ('accel_0_100', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('economy_city', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('economy_highway', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('emission_standard', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_spec', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='TireSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('all', 'All'), ('front', 'Front'), ('rear', 'Rear')], default='all', max_length=10)),
                ('size', models.CharField(max_length=40)),
                ('pressure_psi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('load_index', models.CharField(blank=True, max_length=10)),
                ('speed_rating', models.CharField(blank=True, max_length=5)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='cars.car')),
            ],
            options={
                'ordering': ['position', 'size'],
            },
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='cars.carmodel')),
            ],
            options={
                'ordering': ['car_model__brand__name', 'car_model__name', 'name'],
                'unique_together': {('car_model', 'name')},
            },
        ),
        migrations.RenameField(
            model_name='car',
            old_name='trim',
            new_name='trim_name',
        ),
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cars',
                to='cars.trim',
            ),
        ),
        migrations.RunPython(migrate_trim_strings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='car',
            name='trim_name',
        ),
        migrations.CreateModel(
            name='OBDCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obd_codes', to='cars.carmodel')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('car_model', 'code')},
            },
        ),
    ]
