# Generated by Django 5.2.17 on 2026-08-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_expand_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
