"""Brand / model catalog for seed_brands (Iranian + international)."""

# Manufacturer company names used by seed_brands --flush (Iranian set).
IRANIAN_MANUFACTURERS = (
    "ایران‌خودرو",
    "سایپا",
    "پارس خودرو",
    "مدیران خودرو",
    "کرمان موتور",
    "بهمن موتور",
    "آرین موتور",
    "فردا موتور",
    "مکث موتور",
    "ماموت خودرو",
    "دیار خودرو",
    "ایلیا موتور",
)

# Nested structure:
#   manufacturer -> brand_name -> list of CarModel names
# Empty model list means seed a single CarModel with the same name as the brand.
IRANIAN_CATALOG = {
    "ایران‌خودرو": {
        "پژو": [
            "۲۰۶ تیپ ۲",
            "۲۰۶ تیپ ۳",
            "۲۰۶ تیپ ۵",
            "۲۰۶ تیپ ۶",
            "۲۰۶ SD V8",
            "۲۰۷ دنده‌ای",
            "۲۰۷ اتوماتیک",
            "۲۰۷ سقف شیشه‌ای",
            "۲۰۷ MC",
            "پارس سال",
            "پارس LX",
            "پارس ELX",
            "پارس TU5",
            "۴۰۵ GLX",
            "۴۰۵ SLX",
            "RD",
            "ROA",
            "301",
        ],
        "سمند": [
            "LX",
            "EF7",
            "سورن",
            "سورن ELX",
            "سورن پلاس",
            "سورن پلاس EF7",
            "سورن پلاس XU7P",
            "سورن پلاس دوگانه‌سوز",
        ],
        "دنا": [
            "دنا",
            "دنا معمولی EF7",
            "دنا پلاس",
            "دنا پلاس EF7",
            "دنا پلاس توربو",
            "دنا پلاس توربو ۶ دنده",
            "دنا پلاس توربو اتوماتیک",
        ],
        "تارا": [
            "تارا دستی",
            "تارا اتوماتیک",
            "تارا V1",
            "تارا V2",
            "تارا V3",
            "تارا V4",
            "تارا V4 LX",
            "تارا اتوماتیک V4",
        ],
        "ری‌را": [
            "ری‌را",
            "ری‌را توربو",
        ],
        "رانا": [
            "رانا",
            "رانا LX",
            "رانا پلاس",
            "رانا پلاس ارتقایافته",
        ],
        "هایما": [
            "S5",
            "S7",
            "S7 توربو",
            "S8",
            "7X",
            "8S",
        ],
        "آریسان": [
            "آریسان",
            "آریسان ۲",
        ],
        "H30 Cross": [],
    },
    "سایپا": {
        "پراید": [
            "111",
            "131",
            "132",
            "141",
            "151",
        ],
        "تیبا": [
            "تیبا",
            "تیبا ۲",
        ],
        "ساینا": [
            "ساینا EX",
            "ساینا S",
            "ساینا S دوگانه‌سوز",
            "ساینا GX",
            "ساینا GX-L",
            "ساینا اتوماتیک",
        ],
        "کوییک": [
            "کوییک",
            "کوییک R",
            "کوییک R پلاس",
            "کوییک R اتوماتیک",
            "کوییک S",
            "کوییک GX",
            "کوییک GX-L",
            "کوییک GXR",
            "کوییک RS",
            "کوییک پلاس",
            "کوییک اتوماتیک",
        ],
        "شاهین": [
            "شاهین GL",
            "شاهین G",
            "شاهین G اتوماتیک",
            "شاهین اتوماتیک",
            "شاهین پلاس",
            "شاهین پلاس اتوماتیک",
        ],
        "اطلس": [
            "اطلس G",
            "اطلس GL",
            "اطلس اتوماتیک",
        ],
        "سهند": [
            "سهند S",
            "سهند S اتوماتیک",
            "سهند G",
            "سهند G اتوماتیک",
        ],
        "آریا": [],
        "زامیاد": [
            "Z24",
            "Z24i",
            "زامیاد دیزل",
            "زامیاد دوگانه‌سوز",
        ],
        "پادرا": [
            "پادرا",
            "پادرا پلاس",
            "پادرا پلاس دوگانه‌سوز",
        ],
        "کارون": [],
        "چانگان": [
            "CS35",
            "CS35 Plus",
            "CS55 Plus",
        ],
    },
    "پارس خودرو": {
        "پارس خودرو": [
            "برلیانس H220",
            "برلیانس H230",
            "برلیانس H320",
            "برلیانس H330",
            "برلیانس C3",
            "برلیانس کراس",
            "رنو تندر 90",
            "رنو پارس تندر",
            "رنو ساندرو",
            "رنو ساندرو استپ‌وی",
            "مگان",
            "ماکسیما",
            "قشقایی (نسخه مونتاژی قدیمی)",
        ],
    },
    "مدیران خودرو": {
        "MVM": [
            "110",
            "315",
            "315 New",
            "315 هاچ‌بک",
            "530",
            "X22",
            "X22 Pro",
            "X22 Pro IE",
            "X33",
            "X33S",
            "X55",
            "X55 Pro",
            "X55 Pro IE",
        ],
        "فونیکس": [
            "FX",
            "FX پریمیوم",
            "FX AWD",
            "Tiggo 7",
            "Tiggo 7 Pro",
            "Tiggo 7 Pro Max",
            "Tiggo 8 Pro",
            "Tiggo 8 Pro Max",
            "Tiggo 8 Pro e+",
            "Arrizo 5",
            "Arrizo 6",
            "Arrizo 6 Pro",
            "Arrizo 8",
        ],
        # Independent brand in the Iranian market (Exeed / Xtrim).
        "اکستریم": [
            "LX",
            "TXL",
            "VX",
            "VX AWD",
        ],
    },
    "کرمان موتور": {
        "جک": [
            "J3",
            "J4",
            "J5",
            "S3",
            "S5",
            "T8",
            "T9",
        ],
        "KMC": [
            "K7",
            "A5",
            "Eagle",
            "X5",
            "X5 Pro",
            "J7",
            "J7 EV",
            "SR3",
            "SR5",
            "X9",
            "E30X",
            "T8",
            "T8 اتوماتیک",
            "T9",
        ],
        "BAC": [
            "X3 Pro",
            "X5",
            "X6",
        ],
    },
    "بهمن موتور": {
        "دیگنیتی": [
            "پرایم",
            "پرستیژ",
            "G7",
        ],
        "فیدلیتی": [
            "پرایم ۵ نفره",
            "پرایم ۷ نفره",
            "پرستیژ ۵ نفره",
            "پرستیژ ۷ نفره",
            "XB1",
        ],
        "ریسپکت": [
            "پرایم",
            "۲",
        ],
        "کاپرا": [
            "کاپرا ۲",
            "U",
            "B",
        ],
        "G9": [],
        "اینرودز": [],
        "بستیون": [
            "T77",
            "NAT",
        ],
        "هاوال": [
            "H6",
            "H9",
        ],
        "مزدا": [
            "3",
            "CX-30",
            "CX-50",
            "2",
        ],
    },
    "آرین موتور": {
        "لاماری": [
            "ایما",
            "ایما HEV",
            "ایما X",
            "ایما هیبرید",
            "تیتا",
            "اکو",
            "نئو",
        ],
    },
    "فردا موتور": {
        "فردا": [
            "SX5",
            "T5",
            "T5 HEV",
            "M4",
            "511",
            "511 Plus",
            "Suba M4",
            "سوبا M4",
        ],
        "FMC": [
            "SX5",
            "T5",
            "T5 HEV",
            "M4",
            "511",
            "511 Plus",
            "Suba M4",
        ],
    },
    "مکث موتور": {
        "لوکانو": [
            "L5",
            "L7",
            "L8",
        ],
        "کلوت": [
            "کلوت",
            "کلوت اتوماتیک",
        ],
        "تیارا": [
            "تیارا",
            "تیارا پرایم",
        ],
    },
    "ماموت خودرو": {
        # ID.4 variants live under international Volkswagen (unique Brand.name).
        "جتا": [
            "VS5",
            "VS7",
            "VA3",
        ],
    },
    "دیار خودرو": {
        "دیار خودرو": [
            "BAIC X7",
            "BAIC X55",
            "BAIC U5",
            "بایک X7",
            "سابرینا",
            "سابرینا هاچ‌بک",
            "BJ40",
            "BJ60",
        ],
    },
    "ایلیا موتور": {
        "ایلیا موتور": [
            "دایون Y5",
            "دایون Y7",
            "دایون V5",
            "موسو گرند خان",
            "موسو گرند خان اکستریم",
        ],
    },
}

# country -> brand_name -> list of CarModel names
INTERNATIONAL_CATALOG = {
    "Japan": {
        "Toyota": [
            "Corolla",
            "Corolla Hybrid",
            "Corolla Cross",
            "Corolla Cross Hybrid",
            "Corolla Levin",
            "Levin Hybrid",
            "Camry",
            "Camry Hybrid",
            "C-HR",
            "C-HR Hybrid",
            "RAV4",
            "RAV4 Hybrid",
            "Yaris",
            "Yaris Hatchback",
            "Yaris Cross",
            "Land Cruiser",
            "Land Cruiser 300",
            "Land Cruiser Prado",
            "Land Cruiser 250",
            "Land Cruiser 70",
            "Hilux",
            "Fortuner",
            "Venza",
            "Crown",
            "Prius",
            "GR86",
            "Supra",
            "bZ4X",
        ],
        "Lexus": [
            "ES250",
            "ES300h",
            "NX200",
            "NX250",
            "NX300h",
            "NX350h",
            "RX350",
            "RX450h",
            "RX500h",
            "IS250",
            "IS300",
            "LS460",
            "LX570",
            "LX600",
            "UX250h",
        ],
        "Nissan": [
            "Sunny",
            "Sylphy",
            "Sylphy e-POWER",
            "Altima",
            "Sentra",
            "X-Trail",
            "Qashqai",
            "Qashqai Honor",
            "Kicks",
            "Pathfinder",
            "Patrol",
            "Navara",
            "Ariya",
            "Murano",
            "Teana",
            "Juke",
        ],
        "Honda": [
            "Civic",
            "Civic Hybrid",
            "Accord",
            "CR-V",
            "CR-V Hybrid",
            "HR-V",
            "ZR-V",
            "e:NS1",
            "e:NP1",
            "Odyssey",
        ],
        "Mazda": [
            "Mazda 3",
            "Mazda 3 Sedan",
            "Mazda CX-30",
            "Mazda CX-5",
            "Mazda CX-50",
            "Mazda CX-60",
            "Mazda CX-90",
            "Mazda 2",
        ],
    },
    "South Korea": {
        "Hyundai": [
            "Elantra",
            "Elantra 2025",
            "Sonata",
            "Sonata Hybrid",
            "Tucson",
            "Tucson Turbo",
            "Santa Fe",
            "Santa Fe Hybrid",
            "Kona",
            "Kona Electric",
            "Creta",
            "Venue",
            "Palisade",
            "Ioniq 5",
            "Ioniq 6",
            "Staria",
        ],
        "Kia": [
            "K3",
            "K5",
            "K8",
            "K9",
            "Seltos",
            "Sportage",
            "Sorento",
            "Carnival",
            "Telluride",
            "EV3",
            "EV4",
            "EV5",
            "EV6",
            "EV9",
            "Ceed",
        ],
    },
    "China": {
        "BYD": [
            "Qin Plus",
            "Qin L",
            "Seal",
            "Seal U",
            "Song Plus",
            "Song Pro",
            "Dolphin",
            "Dolphin Mini",
            "Yuan Plus",
            "Atto 3",
            "Han",
            "Tang",
            "Leopard 5",
            "Shark",
        ],
        "GAC": [
            "Empow",
            "Emkoo",
            "Emkoo Hybrid",
            "GS3",
            "GS4",
            "GS8",
            "M8",
            "Aion Y",
            "Aion V",
        ],
        "Changan": [
            "CS35 Plus",
            "CS55 Plus",
            "CS75 Plus",
            "UNI-T",
            "UNI-K",
            "UNI-V",
            "UNI-S",
            "Hunter",
            "Lumin",
        ],
        "Geely": [
            "Coolray",
            "Emgrand",
            "Geometry C",
            "Emgrand L",
            "Starray",
            "Monjaro",
            "Preface",
            "EX5",
            "Galaxy L7",
        ],
        "Haval": [
            "H6",
            "H6 Hybrid",
            "H9",
            "Jolion",
            "Jolion Hybrid",
            "Dargo",
            "Big Dog",
            "Tank 300",
        ],
        "Jetour": [
            "X70",
            "X70 Plus",
            "X90 Plus",
            "X90",
            "Dashing",
            "Traveller",
        ],
        "JAC": [
            "JS3",
            "JS4",
            "JS6",
            "JS7",
            "J7",
            "T8",
            "T9",
        ],
        "Chery": [
            "Tiggo 4",
            "Tiggo 7",
            "Tiggo 7 Pro",
            "Tiggo 8",
            "Tiggo 8 Pro",
            "Tiggo 8 Pro Max",
            "Arrizo 5",
            "Arrizo 6",
            "Arrizo 8",
        ],
        "JAECOO": [
            "J5",
            "J7",
            "J8",
        ],
        "Exeed": [
            "LX",
            "TXL",
            "VX",
            "VX AWD",
        ],
        "Tank": [
            "Tank 300",
            "Tank 400",
            "Tank 500",
            "Tank 700",
        ],
        "BAIC": [
            "X3",
            "X5",
            "X7",
            "BJ40",
            "BJ60",
            "BJ80",
            "U5",
        ],
        "Dongfeng": [
            "Shine",
            "Shine Max",
            "T5 Evo",
            "Aeolus",
            "Nammi Box",
            "Forthing T5",
            "Forthing Friday",
            "M-Hero",
        ],
        "Skywell": [
            "ET5",
            "ET5 Plus",
            "BE11",
            "Nebka Hybrid",
        ],
        "SWM": [
            "G01",
            "G01F",
            "G05",
        ],
        "DFSK": [
            "Glory 500",
            "Glory 580",
            "Glory 580 Pro",
            "Glory IX5",
            "SX5",
        ],
        "Forthing": [
            "T5 Evo",
            "Friday",
            "U-Tour",
            "Yacht",
        ],
        "Bestune": [
            "T77",
            "T99",
            "B70",
            "NAT",
        ],
        "Hongqi": [
            "H5",
            "H7",
            "H9",
            "HS5",
            "HS7",
            "E-HS9",
        ],
        "MG": [
            "MG3",
            "MG4",
            "MG5",
            "MG GT",
            "MG ZS",
            "MG ZS EV",
            "MG HS",
            "MG7",
        ],
    },
    "Germany": {
        "Volkswagen": [
            "Golf",
            "Passat",
            "Jetta",
            "Tiguan",
            "T-Roc",
            "Teramont",
            "ID.3",
            "ID.4",
            "ID.4 Pure",
            "ID.4 Pro",
            "ID.6",
            "ID.7",
        ],
        "BMW": [
            "116i",
            "118i",
            "218i",
            "220i",
            "225",
            "320i",
            "325i",
            "330i",
            "520i",
            "530i",
            "730Li",
            "X1",
            "X2",
            "X3",
            "X4",
            "X5",
            "X6",
            "X7",
            "iX1",
            "iX3",
            "i4",
            "i5",
            "i7",
            "iX",
            "Z4",
        ],
        "Mercedes-Benz": [
            "A-Class",
            "B-Class",
            "C-Class",
            "E-Class",
            "S-Class",
            "CLA",
            "CLS",
            "GLA",
            "GLB",
            "GLC",
            "GLE",
            "GLS",
            "G-Class",
            "EQE",
            "EQS",
            "EQA",
            "EQB",
            "EQE SUV",
            "EQS SUV",
        ],
        "Audi": [
            "A3",
            "A4",
            "A5",
            "A6",
            "A7",
            "A8",
            "Q3",
            "Q4 e-tron",
            "Q5",
            "Q5 e-tron",
            "Q7",
            "Q8",
            "Q8 e-tron",
            "e-tron GT",
        ],
    },
    "Czech Republic": {
        "Skoda": [
            "Kamiq",
            "Karoq",
            "Kodiaq",
            "Superb",
            "Octavia",
            "Scala",
            "Kushaq",
            "Enyaq",
            "Kodiaq iV",
        ],
    },
    "Sweden": {
        "Volvo": [
            "XC40",
            "XC40 Recharge",
            "XC60",
            "XC70",
            "XC90",
            "S60",
            "S90",
            "C40",
            "EX30",
            "EX40",
            "EX90",
        ],
    },
    "United Kingdom": {
        "MINI": [
            "Cooper",
            "Cooper S",
            "Countryman",
            "Clubman",
            "Countryman S",
        ],
        "Land Rover": [
            "Defender",
            "Discovery",
            "Discovery Sport",
            "Range Rover",
            "Range Rover Sport",
            "Range Rover Velar",
            "Range Rover Evoque",
        ],
    },
    "France": {
        "Peugeot": [
            "206",
            "207",
            "208",
            "301",
            "308",
            "408",
            "508",
            "2008",
            "3008",
            "5008",
        ],
        "Renault": [
            "Logan",
            "Sandero",
            "Sandero Stepway",
            "Duster",
            "Captur",
            "Koleos",
            "Megane",
            "Megane E-Tech",
            "Arkana",
            "Clio",
            "Fluence",
            "Latitude",
            "Talisman",
            "Symbol",
            "L90",
        ],
    },
    "Italy": {
        "Fiat": [
            "500",
            "500X",
            "Tipo",
            "Doblo",
            "Panda",
        ],
    },
    "Spain": {
        "Seat": [
            "Ibiza",
            "Leon",
            "Ateca",
            "Arona",
        ],
    },
}


def normalize_model_name(brand_name: str, model_name: str) -> str:
    """Strip a redundant leading brand prefix from a model label."""
    prefixes = (f"{brand_name} ", f"{brand_name}‌")
    for prefix in prefixes:
        if model_name.startswith(prefix):
            return model_name[len(prefix) :].strip()
    return model_name


def international_brand_names() -> frozenset[str]:
    names: set[str] = set()
    for brands in INTERNATIONAL_CATALOG.values():
        names.update(brands.keys())
    return frozenset(names)
